# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    orgId: 1
    basicAuth: false
    isDefault: false
    editable: false
    version: 1
    jsonData:
      httpMethod: GET

  - name: Tempo
    uid: tempo
    type: tempo
    url: http://tempo:3200
    access: proxy
    orgId: 1
    basicAuth: false
    isDefault: true
    editable: false
    version: 1
    apiVersion: 1
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      streamingEnabled:
        search: true
